GET http://localhost:5045

###
GET http://localhost:5045/games

###
GET http://localhost:5045/games/1

###
POST http://localhost:5045/games
Content-Type: application/json

{
    "genre": "Simulation",
    "price": 14.99,
    "releaseDate": "2016-02-06"
}

###
PUT http://localhost:5045/games/2
Content-Type: application/json

{
    "genre": "RPG",
    "price": 39.99,
    "releaseDate": "2020-12-10"
}

###
DELETE http://localhost:5045/games/4